/**
 * Blur placeholders LQIP (Low Quality Image Placeholders) das fotos da fazenda.
 * Gerados via PIL: 16px max, JPEG quality 40, sem EXIF. ~450 chars cada.
 * Uso: <Image placeholder="blur" blurDataURL={BLUR.fazendaChegada} />
 */
export const BLUR = {
  fazendaChegada:
    "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQAAkDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAQIEBf/EACQQAAAEAgsAAAAAAAAAAAAAAAABAgMTIQQFERIkMVFUcZKh/8QAFAEBAAAAAAAAAAAAAAAAAAAAA//EABoRAAICAwAAAAAAAAAAAAAAAAABAgMTQVH/2gAMAwEAAhEDEQA/AFUdHlY6mfnIGH3DXchiuVizAU0lozvZqNQgip0DK6e0FjXT/9k=",
  cafeFrutosVerdes:
    "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQAAkDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAgME/8QAIBABAAAEBwEAAAAAAAAAAAAAAQACAxEEEyExQVGRYf/EABUBAQEAAAAAAAAAAAAAAAAAAAID/8QAFhEBAQEAAAAAAAAAAAAAAAAAABES/9oADAMBAAIRAxEAPwDIo0ynvd1Xj4QcrD9PsHEShKShdZtr6kSyKnVX0iWaFf/Z",
  fazendaLavoura:
    "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQAAkDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAgMEBf/EACMQAAIBAwEJAAAAAAAAAAAAAAECAAMEETETFBUhQVJTkqH/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/8QAGBEAAgMAAAAAAAAAAAAAAAAAAAEEE1H/2gAMAwEAAhEDEQA/AFmnRJULWQlhkc9YW7jvX2EzltNpbsrnBfQnpJeEt5vkVSNQdTP/2Q==",
  peneiraCafe:
    "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQAAwDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABAIF/8QAIBAAAgEEAQUAAAAAAAAAAAAAAQIDABEhMQQSExRhcf/EABQBAQAAAAAAAAAAAAAAAAAAAAL/xAAWEQEBAQAAAAAAAAAAAAAAAAABABH/2gAMAwEAAhEDEQA/ABTmGPgzsYu3M4tY3IPw6rEXVNUtoxsVG8VPShz44z7oDJwv/9k=",
} as const;

/** Resolve blur a partir do path da imagem em /public. */
export function blurFor(src: string): string | undefined {
  if (src.includes("fazenda-chegada")) return BLUR.fazendaChegada;
  if (src.includes("cafe-frutos-verdes")) return BLUR.cafeFrutosVerdes;
  if (src.includes("fazenda-lavoura")) return BLUR.fazendaLavoura;
  if (src.includes("peneira-cafe")) return BLUR.peneiraCafe;
  return undefined;
}
